### ISSUE TITLE
Compilation error after update to 3.0

### ISSUE THREAD

**Issue by mdpetters** [andizuend/AIOMFAC#2]
Thanks for updating the code with new features. 

When running make ```make all``` I get the following error

```bash
f951: Error: Cannot open file ‘./Mod_PureViscosPar.f90’
<built-in>: Fatal Error: cannot open input file: ./Mod_PureViscosPar.f90
```

Removing the underscore error in the Makefile fixes this issue. However, it still fails after this:

```bash
gfortran  -c  -O3 -fbounds-check -ffree-line-length-none -Wconversion    -c	./ModSRunifac.f90
./ModSRunifac.f90:42:5:

   42 | USE ModSRparam, ONLY : ARR, BRR, CRR, SR_RR, SR_QQ
      |     1
Fatal Error: Cannot open module file ‘modsrparam.mod’ for reading at (1): No such file or directory
```

I played a little bit more with the ```Makefile```  and manual compilation and made some progress, but ultimately couldn't find a solution to build an executable.

**Comment by andizuend** [comment]
Hi Markus, 
Thanks for bringing up this issue. It was caused by an older `Makefile`. The model code, including certain modules like `ModPureViscosPar.f90`, have been updated and reorganized, which led to incompatibility with the older Makefile. 
I've updated the Makefile and fixed an issue; please see the latest file versions from the [v3.01 release](https://github.com/andizuend/AIOMFAC/tree/v3.01).
Also, starting with v3.00, I've added a simple compilation command line in file build_command_line.txt that one could use via copy&paste instead of running the Makefile.
Best regards,
Andi

**Comment by mdpetters** [comment]
Thanks Andi - that did the trick. I think the issue can be closed. I'm excited to start working with the new model.
